export const Routes = {
    home: '/',
    reviewGuesser: '/review-guesser',
    reviewGuesser1: '/review-guesser/1',
    reviewGuesser2: '/review-guesser/2',
    reviewGuesser3: '/review-guesser/3',
    reviewGuesser4: '/review-guesser/4',
    reviewGuesser5: '/review-guesser/5',
    leaderboard: '/review-guesser/leaderboard',
    leaderboardMonthly: '/review-guesser/leaderboard/monthly',
    leaderboardWeekly: '/review-guesser/leaderboard/weekly',
    leaderboardToday: '/review-guesser/leaderboard/today',
    archive: '/review-guesser/archive',
    imprint: '/imprint',
    privacy: '/privacy',
}
