export const Routes = {
    home: '/',
    reviewGuesser: '/review-guesser',
    reviewGuesser1: '/review-guesser/1',
    reviewGuesser2: '/review-guesser/2',
    reviewGuesser3: '/review-guesser/3',
    reviewGuesser4: '/review-guesser/4',
    reviewGuesser5: '/review-guesser/5',
    leaderboard: '/review-guesser/leaderboard',
    leaderboardSeason: '/review-guesser/leaderboard/season',
    leaderboardWeekly: '/review-guesser/leaderboard/weekly',
    leaderboardToday: '/review-guesser/leaderboard/today',
    leaderboardHardest: '/review-guesser/leaderboard/hardest',
    leaderboardPerfectDays: '/review-guesser/leaderboard/perfect-days',
    archive: '/review-guesser/archive',
    randomArchive: '/review-guesser/random',
    seasons: '/review-guesser/seasons',
    seasonDetail: (seasonNumber: number | string) => `/review-guesser/seasons/${seasonNumber}`,
    imprint: '/imprint',
    privacy: '/privacy',
    howToPlay: '/how-to-play',
}
