name: coolify
spring:
  cache:
    caffeine:
      spec: maximumSize=500,expireAfterWrite=12h,refreshAfterWrite=1h #https://github.com/ben-manes/caffeine/wiki/Refresh
management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: "health" # https://www.baeldung.com/spring-boot-actuators
  endpoint:
    health:
      show-details: never
