name: coolify
spring:
  cache:
    caffeine:
      spec: maximumSize=500,expireAfterWrite=12h,refreshAfterWrite=1h #https://github.com/ben-manes/caffeine/wiki/Refresh
management:
  server:
    port: ${MANAGEMENT_SERVER_PORT:8081}
  endpoints:
    web:
      exposure:
        include: ${MANAGEMENT_ENDPOINTS_EXPOSURE:health,prometheus} # https://www.baeldung.com/spring-boot-actuators
  endpoint:
    health:
      show-details: never
