### GET request to load all steam app ids
GET https://api.steampowered.com/ISteamApps/GetAppList/v0002/?key=STEAMKEY&format=json

### GET request to load single steam app
GET https://store.steampowered.com/api/appdetails?appids={{appId}}&key={{apikey}}

### GET game list
GET https://api.steampowered.com/IStoreService/GetAppList/v1/?include_games=true&key={{apikey}}&max_results=50000

### GET game list paging, if "have_more_results === true"
GET https://api.steampowered.com/IStoreService/GetAppList/v1/?include_games=true&key={{apikey}}&max_results=50000&
    last_appid=1533580
